version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: x402-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: x402_middleware
      POSTGRES_USER: x402_user
      POSTGRES_PASSWORD: x402_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U x402_user -d x402_middleware"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - x402-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: x402-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass x402_redis_password
    volumes:
      - redis_data:/data
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - x402-network

  # API Server
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: x402-api
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://x402_user:x402_password@postgres:5432/x402_middleware?schema=public
      - REDIS_URL=redis://:x402_redis_password@redis:6379
    volumes:
      - ./apps/api:/app
      - /app/node_modules
      - ./packages:/packages:ro
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - x402-network

  # Web Client
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: x402-web
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3001
      - NEXT_PUBLIC_CHAIN_ID=84532
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - ./packages:/packages:ro
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - x402-network

  # Adminer (Database Management Tool)
  adminer:
    image: adminer:4.8.1
    container_name: x402-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - x402-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  x402-network:
    driver: bridge 